name: deploy
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: mkdir temp/
      - run: echo "${{ secrets.KEY }}" > temp/key
      - run: chmod 700 temp/key
      - run: ssh -o 'StrictHostKeyChecking no' -i temp/key ${{ secrets.USERNAME }}@${{ secrets.HOST }} sudo update-site.sh
      - run: rm -rf temp/